apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-k8s-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hanparkk/spring-k8s-demo.git
    targetRevision: HEAD
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-k8s-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true