apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-demo
  namespace: spring-k8s-demo
  labels:
    app: spring-k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-k8s-demo
  template:
    metadata:
      labels:
        app: spring-k8s-demo
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: spring-k8s-demo
        image: 192.168.56.10:30500/spring-k8s-demo:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi