apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-demo-service
  namespace: spring-k8s-demo
  labels:
    app: spring-k8s-demo
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30082
    protocol: TCP
    name: http
  selector:
    app: spring-k8s-demo